services:
  postgres:
    image: postgres:16
    container_name: workit_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - workit_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: workit_postgres
    depends_on:
      - postgres
    networks:
      - workit_network
          
volumes:
  postgres-data:

networks:
  workit_network:
    driver: bridge  